version: "3"

vars:
  YTDL_OPTIONS: -ic --extract-audio --audio-format mp3 --audio-quality 0

tasks:

  dupes:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - fdupes -r .

  dl-audio:  # invoke: tg dl-audio -- url
    cmds:
      - yt-dlp {{.YTDL_OPTIONS}} {{.CLI_ARGS}}

  dl-audio-list:
    cmds:
      - yt-dlp {{.YTDL_OPTIONS}} --yes-playlist -o "%(title)s-%(id)s.%(ext)s" {{.CLI_ARGS}}

  audio-meta:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - beet import .
