version: "3"

tasks:
  venv:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - python -m venv venv

  svenv:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - source ./venv/bin/activate

  dupes:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - fdupes -r .
