[colors.primary]
background = "0x131517"
foreground = "0xdadada"

[colors.normal]
yellow = "0xebcb8b"
red = "0xbf616a"
magenta = "0xb48ead"
blue = "0x81a1c1"
cyan = "0x82bebc"
green = "0x9cbf87"
black = "0x1e1e1e"
white = "0xc0c0c0"

[colors.bright]
yellow = "0xf1ca81"
red = "0xcd5a68"
magenta = "0xb386a7"
blue = "0x78a2c4"
cyan = "0x8fc4c3"
green = "0x98bf5b"
black = "0x52565f"
white = "0xc0c0c0"
