[misc]
assume_yes = true

# disable specific steps
disable = ["containers", "git_repos", "helm", "pip3", "uv"]

# ignore_failures = []

# no_retry = true

run_in_tmux = false

# Do not set the terminal title
set_title = false

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
# cleanup = true

# Skip sending a notification at the end of a run
skip_notify = true

[composer]
# self_update = true

# Custom commands
[commands]
"Podman" = "podman auto-update"
#"Prezto Update" = "$HOME/.config/zsh/.zprezto/init.zsh zprezto-update"

# Causes Topgrade to rename itself during the run to allow package managers
# to upgrade it. Use this only if you installed Topgrade by using a package
# manager such as Scoop or Cargo
# self_rename = true

[firmware]
# Offer to update firmware; if false just check for and display available updates
upgrade = true

[flatpak]
# Use sudo for updating the system-wide installation
use_sudo = false
