########################
# taps
########################

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

tap "danielfoehrkn/switch"
tap "go-task/tap"
tap "zegervdv/zathura"

########################
# brew
########################

brew "ansible"
brew "topgrade"
brew "thefuck"
brew "tmux"
brew "rclone"
brew "fping"

brew "bat"
brew "lsd"
brew "tree"
brew "lf"
brew "fd"
brew "fzf"
brew "gnu-tar"
brew "jq"
brew "unzip"
brew "go-task/tap/go-task"
brew "btop"
brew "lnav"

brew "wget"
brew "telnet"
brew "httpie"

brew "tldr"
brew "hyperfine"
brew "neofetch"
brew "onefetch"

brew "cri-tools"
brew "kubectx"
brew "minikube"
brew "openshift-cli"
brew "danielfoehrkn/switch/switch"

brew "git"
brew "git-delta"

brew "go-bindata"
brew "golangci-lint"

brew "micro"
brew "neovim"
brew "zathura"
brew "zathura-pdf-poppler"
brew "pandoc"

brew "openjdk"

brew "bash"
brew "zsh"

brew "autoconf"
brew "coreutils"
brew "pkg-config"

########################
# casks
########################

# cask "firefox"

cask "alacritty"
cask "rancher"
cask "github"

cask "goland"
cask "pycharm-ce"
cask "visual-studio-code"
cask "miniconda"

cask "tableplus"
cask "mongodb-compass"

cask "karabiner-elements"
cask "oracle-jdk"
cask "postman"

cask "xournal-plus-plus"

########################
# fonts
########################

cask "font-jetbrains-mono-nerd-font"
